
-- Debug eval run: Check status
CALL EXECUTE_AI_EVALUATION(
  'STATUS',
  OBJECT_CONSTRUCT('run_name', 'SUPPORT_AGENT_CORTEX_EVAL_RUN'),
  '@CUST_SUPPORT_DEMO.SUPPORT.EVAL_CONFIG_STAGE/support_agent_eval_config.yaml'
);

-- Debug eval run: Get detailed results
SELECT * FROM TABLE(SNOWFLAKE.LOCAL.GET_AI_EVALUATION_DATA(
  'CUST_SUPPORT_DEMO',
  'SUPPORT',
  'SUPPORT_AGENT',
  'CORTEX AGENT',
  'SUPPORT_AGENT_CORTEX_EVAL_RUN'
));

-- Debug eval run: Check errors and warnings
SELECT * FROM TABLE(SNOWFLAKE.LOCAL.GET_AI_OBSERVABILITY_LOGS(
  'CUST_SUPPORT_DEMO',
  'SUPPORT',
  'SUPPORT_AGENT',
  'CORTEX AGENT'
))
WHERE TRUE
  AND (record:"severity_text" = 'ERROR' OR record:"severity_text" = 'WARN')
  AND record_attributes:"snow.ai.observability.run.name" = 'SUPPORT_AGENT_CORTEX_EVAL_RUN';

-- Debug eval run: Find failed eval tasks in task history
SELECT *
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 50,
    ERROR_ONLY => TRUE
))
WHERE NAME ILIKE '%AI_EVALUATION%' OR NAME ILIKE '%EVAL%'
ORDER BY SCHEDULED_TIME DESC;

-- Debug eval run: All recent eval-related task runs (including succeeded)
SELECT NAME, STATE, ERROR_CODE, ERROR_MESSAGE, QUERY_TEXT, SCHEDULED_TIME, COMPLETED_TIME
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 100
))
WHERE NAME ILIKE '%AI_EVALUATION%' OR NAME ILIKE '%EVAL%'
ORDER BY SCHEDULED_TIME DESC;

SELECT GROUND_TRUTH FROM CUST_SUPPORT_DEMO.SUPPORT.EVAL_DATA;

SELECT * FROM CUST_SUPPORT_DEMO.SUPPORT.SUPPORT_EVALSET VERSION 'SYSTEM_AI_OBS_CORTEX_AGENT_DATASET_VERSION_DO_NOT_DELETE' LIMIT 5;